package dev.isxander.debugify

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import kotlin.collections.filterIsInstance

@CacheableTask
abstract class GeneratePatchedTableTask : DefaultTask() {
	@get:Input
	abstract val bugs: ListProperty<PatchedFileEntry>

	@get:OutputFile
	abstract val output: RegularFileProperty

	@TaskAction
	fun generatePatchedTable() {
		val entries = bugs.get()

		val patched = entries.filterIsInstance<PatchedFileEntry.Patched>()
		val clientPatched = patched.filter { it.env.isClient }
		val serverPatched = patched.filter { it.env.isServer }
		fun generatePatchedRows(entries: List<PatchedFileEntry.Patched>) =
			entries.joinToString("\n") { "- | ${it.type.friendlyName} | [${it.bugId}](https://mojira.dev/${it.bugId}) | ${MojiraBug.fetchDescription(it.bugId)} | ${if (it.tested) "Yes" else "No"} |" }

		val previous = entries.filterIsInstance<PatchedFileEntry.Previous>()

		val timestamp = LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME)

		val markdownTable = """
            - <!--
            - !!!! DO NOT UPDATE THIS FILE MANUALLY !!!!
            - Generated by `./gradlew generatePatchedTable`
            - Generated $timestamp
            - -->
            -
            - # List of Patched Bugs
            - ## Unpatched in vanilla
            - ### Client side
            - | Type | Bug ID | Name | Tested |
            - |------|--------|------|--------|
            ${generatePatchedRows(clientPatched)}

            - ### Server side (both)
            - | Type | Bug ID | Name | Tested |
            - |------|--------|------|--------|
            ${generatePatchedRows(serverPatched)}

            - ## Previously patched
            - Bugs that this mod has patched in the past, but has since been fixed by a vanilla update.

            - | Bug ID | Name | Fixed Version |
            - |--------|------|---------------|
            ${previous.joinToString("\n") { "- | [${it.bugId}](https://mojira.dev/${it.bugId}) | ${MojiraBug.fetchDescription(it.bugId)} | ${it.patchVersion} |" }}
        """.trimMargin("-")

		val outputFile = output.get().asFile
		outputFile.parentFile.mkdirs()
		outputFile.writeText(markdownTable)
	}
}
