name: Build & Test

on: [push, pull_request]

permissions:
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with gradle

    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Check with Gradle
        run: ./gradlew check

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/attest@v4
        with:
          subject-path: build/libs/*.jar

      - uses: actions/upload-artifact@v7
        with:
          path: build/libs/*
