name: Bug Status Check

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check bug status

    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Check bug status with Gradle
        run: ./gradlew checkBugFixes
